// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseManagament.Persistence.Concrete.Context;

#nullable disable

namespace PurchaseManagament.Persistence.Migrations
{
    [DbContext(typeof(PurchaseManagamentContext))]
    [Migration("20231124080334_material")]
    partial class material
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ADDRESS")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("ManagerThreshold")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MANAGER_THRESHOLD");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("COMPANIES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Varsayılan Adres",
                            ManagerThreshold = 0m,
                            Name = "Varsayılan Şirket"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.CompanyDepartment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("COMPANY_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<long>("DepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("DEPARTMENT_ID")
                        .HasColumnOrder(3);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("COMPANY_DEPARTMENTS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CompanyId = 1L,
                            DepartmentId = 1L
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.CompanyStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("COMPANY_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCT_ID")
                        .HasColumnOrder(3);

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("QUANTITY")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("COMPANY_STOCK", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CURRENCY_NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("CURRENCIES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "TRY"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "USD"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "AUD"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "DKK"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "EUR"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "GBP"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "CHF"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "SEK"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "CAD"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "KWD"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "NOK"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "SAR"
                        },
                        new
                        {
                            Id = 13L,
                            Name = "JPY"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DEPARTMENT_NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("DEPARTMENTS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Varsayılan Departman"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BirthYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("BIRTH_YEAR")
                        .HasColumnOrder(6);

                    b.Property<long>("CompanyDepartmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("COMPANY_DEPARTMENT_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("GENDER")
                        .HasColumnOrder(7);

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ID_NUMBER")
                        .HasColumnOrder(5);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(3);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SURNAME")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("CompanyDepartmentId");

                    b.ToTable("EMPLOYEES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BirthYear = "1999",
                            CompanyDepartmentId = 1L,
                            Gender = 0,
                            IdNumber = "12345678910",
                            Name = "Varsayılan",
                            Surname = "Çalışan"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.EmployeeDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS")
                        .HasColumnOrder(4);

                    b.Property<string>("ApprovedCode")
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("APPROVED_CODE")
                        .HasColumnOrder(9);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAIL")
                        .HasColumnOrder(5);

                    b.Property<bool?>("EmailOk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EMAIL_OK")
                        .HasColumnOrder(8);

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EMPLOYEE_ID")
                        .HasColumnOrder(2);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PASSWORD")
                        .HasColumnOrder(6);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PHONE")
                        .HasColumnOrder(7);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USERNAME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EMPLOYEE_DETAILS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Varsayılan Adres",
                            ApprovedCode = "111111",
                            Email = "default@mail.com",
                            EmailOk = true,
                            EmployeeId = 1L,
                            Password = "kVU41twDyttUL/SM7IO0vQ==",
                            Phone = "12345678910",
                            Username = "Varsayılan"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.EmployeeRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EMPLOYEE_ID")
                        .HasColumnOrder(2);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("ROLE_ID")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("EMPLOYEE_ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EmployeeId = 1L,
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.ImgProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("IMAGE_SRC")
                        .HasColumnOrder(3);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<long>("ProductId")
                        .HasColumnType("BigInt")
                        .HasColumnName("PRODUCT_ID")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("IMG_PRODUCT", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<string>("ImageSrc")
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("IMAGE_SRC")
                        .HasColumnOrder(4);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<long>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(3);

                    b.Property<decimal>("TRY_Rate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TRY_RATE")
                        .HasColumnOrder(5);

                    b.Property<Guid>("UUID")
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.ToTable("INVOICES", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("APPROVED_DATE")
                        .HasColumnOrder(7);

                    b.Property<long?>("ApprovingEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("APPROVING_EMPLOYEE_ID")
                        .HasColumnOrder(6);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DETAILS")
                        .HasColumnOrder(4);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("PRODUCT_ID")
                        .HasColumnOrder(3);

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("QUANTITY")
                        .HasColumnOrder(5);

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint")
                        .HasColumnName("REQUEST_ID")
                        .HasColumnOrder(2);

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("ApprovingEmployeeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId");

                    b.ToTable("MATERIALS", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.MaterialOffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint")
                        .HasColumnName("MATERIAL_ID")
                        .HasColumnOrder(3);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<long>("OfferId")
                        .HasColumnType("bigint")
                        .HasColumnName("OFFER_ID")
                        .HasColumnOrder(2);

                    b.Property<decimal>("OfferedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OfferId");

                    b.ToTable("MATERIAL_OFFERS", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.MeasuringUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("MEASURING_UNIT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Adet"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Metre"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Metrekare"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Metre Küp"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Litre"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Offer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AboveThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ABOVE_THRESHOLD")
                        .HasColumnOrder(6);

                    b.Property<long?>("ApprovingEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("APPROVING_EMPLOYEE_ID")
                        .HasColumnOrder(5);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<long>("CurrencyId")
                        .HasColumnType("BigInt")
                        .HasColumnName("CURRENCY_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("DETAILS")
                        .HasColumnOrder(7);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(8);

                    b.Property<long>("SupplierId")
                        .HasColumnType("BigInt")
                        .HasColumnName("SUPPLIER_ID")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("ApprovingEmployeeId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("SupplierId");

                    b.ToTable("OFFERS", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(4);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<long>("MeasuringUnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("MEASURING_UNIT_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("MeasuringUnitId");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION")
                        .HasColumnOrder(3);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("REQUEST_EMPLOYEE_ID")
                        .HasColumnOrder(2);

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("STATUS")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestEmployeeId");

                    b.ToTable("REQUESTS", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ROLE_NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("ROLES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Satın Alma Sorumlusu"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Onay"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Talep"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Birim Sorumlusu"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Muhasebe"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Genel Müdür"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Y.K Başkanı"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Stok Sorumlusu"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Birim Müdürü"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.StockOperations", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyStockId")
                        .HasColumnType("bigint")
                        .HasColumnName("COMPANY_STOCK_ID")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("QUANTITY")
                        .HasColumnOrder(4);

                    b.Property<long>("ReceivingEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("RECEIVING_EMPLOYEE")
                        .HasColumnOrder(3);

                    b.HasKey("Id");

                    b.HasIndex("CompanyStockId");

                    b.HasIndex("ReceivingEmployeeId");

                    b.ToTable("STOCK_OPERATIONS", (string)null);
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ADDRESS")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY_ID")
                        .HasColumnOrder(51);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATE_DATE")
                        .HasColumnOrder(50);

                    b.Property<string>("CreatedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CREATE_IP")
                        .HasColumnOrder(52);

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE")
                        .HasColumnOrder(56)
                        .HasDefaultValueSql("1");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("IS_DELETED")
                        .HasColumnOrder(57)
                        .HasDefaultValueSql("0");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODIFIED_BY_ID")
                        .HasColumnOrder(54);

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MODIFIED_DATE")
                        .HasColumnOrder(53);

                    b.Property<string>("ModifiedIP")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MODIFIED_IP")
                        .HasColumnOrder(55);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("SUPPLIERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Şirket Adres",
                            Name = "Şirket Stok"
                        });
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.CompanyDepartment", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Company", "Company")
                        .WithMany("CompanyDepartments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("COMPANY_DEPARTMENT_COMPANIES");

                    b.HasOne("PurchaseManagament.Domain.Entities.Department", "Department")
                        .WithMany("CompanyDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("COMPANY_DEPARTMENT_DEPARTMENTS");

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.CompanyStock", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Company", "Company")
                        .WithMany("CompanyStocks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("COMPANY_STOCK_COMPANIES");

                    b.HasOne("PurchaseManagament.Domain.Entities.Product", "Product")
                        .WithMany("CompanyStocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("COMPANY_DEPARTMENT_PRODUCTS");

                    b.Navigation("Company");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Employee", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.CompanyDepartment", "CompanyDepartment")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompanyDepartment");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.EmployeeDetail", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Employee", "Employee")
                        .WithOne("EmployeeDetail")
                        .HasForeignKey("PurchaseManagament.Domain.Entities.EmployeeDetail", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("EMPLOYEE_DETAIL");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.EmployeeRole", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PurchaseManagament.Domain.Entities.Role", "Role")
                        .WithMany("EmployeeRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.ImgProduct", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Product", "Product")
                        .WithOne("ImgProduct")
                        .HasForeignKey("PurchaseManagament.Domain.Entities.ImgProduct", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PRODUCT_IMG");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Offer", "Offer")
                        .WithOne("Invoice")
                        .HasForeignKey("PurchaseManagament.Domain.Entities.Invoice", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Material", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Employee", "ApprovedEmployee")
                        .WithMany("ApprovedMaterials")
                        .HasForeignKey("ApprovingEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("MATERIAL_APPROVING_EMPLOYEE");

                    b.HasOne("PurchaseManagament.Domain.Entities.Product", "Product")
                        .WithMany("Materials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("MATERIAL_PRODUCT");

                    b.HasOne("PurchaseManagament.Domain.Entities.Request", "Request")
                        .WithMany("Materials")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("MATERIAL_REQUEST");

                    b.Navigation("ApprovedEmployee");

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.MaterialOffer", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Material", "Material")
                        .WithMany("MaterialOffers")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MATERIAL_OFFERS_MATERIAL");

                    b.HasOne("PurchaseManagament.Domain.Entities.Offer", "Offer")
                        .WithMany("MaterialOffers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MATERIAL_OFFERS_OFFER");

                    b.Navigation("Material");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Offer", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Employee", "ApprovingEmployee")
                        .WithMany("Offers")
                        .HasForeignKey("ApprovingEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PurchaseManagament.Domain.Entities.Currency", "Currency")
                        .WithMany("Offers")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PurchaseManagament.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Offers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovingEmployee");

                    b.Navigation("Currency");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Product", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.MeasuringUnit", "MeasuringUnit")
                        .WithMany("Products")
                        .HasForeignKey("MeasuringUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PRODUCT_MEASURING_UNITS");

                    b.Navigation("MeasuringUnit");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Request", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.Product", null)
                        .WithMany("Requests")
                        .HasForeignKey("ProductId");

                    b.HasOne("PurchaseManagament.Domain.Entities.Employee", "RequestEmployee")
                        .WithMany("EmployeeRequests")
                        .HasForeignKey("RequestEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("REQUEST_REQUEST_EMPLOYEE");

                    b.Navigation("RequestEmployee");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.StockOperations", b =>
                {
                    b.HasOne("PurchaseManagament.Domain.Entities.CompanyStock", "CompanyStock")
                        .WithMany("StockOperations")
                        .HasForeignKey("CompanyStockId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("STOCK_OPERATIONS_COMPANY_STOCK");

                    b.HasOne("PurchaseManagament.Domain.Entities.Employee", "Employee")
                        .WithMany("StockOperations")
                        .HasForeignKey("ReceivingEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("STOCK_OPERATIONS_RECEIVING_EMPLOYEE");

                    b.Navigation("CompanyStock");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyDepartments");

                    b.Navigation("CompanyStocks");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.CompanyDepartment", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.CompanyStock", b =>
                {
                    b.Navigation("StockOperations");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Department", b =>
                {
                    b.Navigation("CompanyDepartments");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ApprovedMaterials");

                    b.Navigation("EmployeeDetail");

                    b.Navigation("EmployeeRequests");

                    b.Navigation("EmployeeRoles");

                    b.Navigation("Offers");

                    b.Navigation("StockOperations");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Material", b =>
                {
                    b.Navigation("MaterialOffers");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.MeasuringUnit", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Offer", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("MaterialOffers");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Product", b =>
                {
                    b.Navigation("CompanyStocks");

                    b.Navigation("ImgProduct");

                    b.Navigation("Materials");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Request", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Role", b =>
                {
                    b.Navigation("EmployeeRoles");
                });

            modelBuilder.Entity("PurchaseManagament.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
